export const FETCH_RECOMMEND_LIST = 'FETCH_RECOMMEND_LIST'
export const FETCH_RECOMMEND_SUCCESS = 'FETCH_RECOMMEND_SUCCESS'
export const FETCH_RECOMMEND_ERROR = 'FETCH_RECOMMEND_ERROR'
export const FETCH_RECOMMEND_SINGLE = 'FETCH_RECOMMEND_SINGLE'

export const SEARCH = 'SEARCH'

export const FETCH_FREE_LIST = 'FETCH_FREE_LIST'
export const FETCH_FREE_SUCCESS = 'FETCH_FREE_SUCCESS'
export const FETCH_FREE_ERROR = 'FETCH_FREE_ERROR'
export const FETCH_FREE_SINGLE = 'FETCH_FREE_SINGLE'
