module.exports = {
  API_DOMAIN_LIST: process.env.REACT_APP_API_DOMAIN_LIST,
  API_DOMAIN_DETAIL: process.env.REACT_APP_API_DOMAIN_DETAIL,
  PROXY_ENDPOINT_LIST: process.env.REACT_APP_PROXY_ENDPOINT_LIST,
  API_ENDPOINT_FREE_LIST: process.env.REACT_APP_ENDPOINT_FREE_LIST,
  API_ENDPOINT_RECOMMEND_LIST: process.env.REACT_APP_ENDPOINT_RECOMMEND_LIST,
  PROXY_ENPOINT_DETAIL: process.env.REACT_APP_PROXY_ENPOINT_DETAIL,
  API_ENDPOINT_DETAIL: process.env.REACT_APP_API_ENDPOINT_DETAIL,
}
